### ISSUE TITLE
Command History Is not Saved

### ISSUE THREAD

**Issue by DeedleFake** [michaelmacinnis/oh#15]
I realize this is more of a feature request than a bug, but I'd definitely call the lack of this feature an issue.

**Comment by michaelmacinnis** [comment]
Command history should now be saved (on Unix and Unix-like systems).

**Comment by DeedleFake** [comment]
Yep, it seems to be working. Thanks.

**Comment by DeedleFake** [comment]
And it's not working on a different computer. Weird. It works in my Arch VM, but not on an actual Arch installation.

**Comment by michaelmacinnis** [comment]
I'll take a look. Oh is trying to write a file in your $HOME directory. It would be weird if it didn't have permission to do that. Do you change the value of $HOME after starting oh? Right now if we fail to read/write the history file failure is silent. I'll make it louder so we can see what is going on.

**Comment by michaelmacinnis** [comment]
@DeedleFake , the latest version of oh should print an error message if there is a problem reading or writing the history file.

**Comment by michaelmacinnis** [comment]
@DeedleFake , is this still an issue?

**Comment by DeedleFake** [comment]
Sorry it took so long to reply.

Yes, this is still an issue. When oh starts, it gives the following error:

> Error reading history: open /home/deedles/.oh_history: no such file or directory

However, it never creates the file or gives any other errors.

**Comment by DeedleFake** [comment]
Alright, found something. If I exit the shell using `exit`, it silently fails to write the history file. If I exit using `^D`, though, then it works fine.

**Comment by michaelmacinnis** [comment]
Should work now.
