### ISSUE TITLE
Backgrounding a Program Crashes the Shell

### ISSUE THREAD

**Issue by DeedleFake** [michaelmacinnis/oh#16]
Running a command in the background, such as `eog &`, causes the shell to crash without an error message the next time a key is pressed.

**Comment by michaelmacinnis** [comment]
I hate to respond with "works for me" but I'm having trouble reproducing the problem you describe. I can launch `eog` in the background and then continue using `oh`:
    > eog &
    # Omitted dconf error messages...
    > ls
    bin	  img  LICENSE	MANUAL.md  pkg	      version.go
    catch.oh  lib  main.go	oh.save    README.md

**Comment by tw4452852** [comment]
I also encounter this problem. I just run a command: `sleep 10 &` in `oh`, it exits immediately...

**Comment by michaelmacinnis** [comment]
@tw4452852 , @DeedleFake , I'll need some more detail to track this down. Can you provide more information about the OS and architecture you are on as well as the version of Go you used to compile oh?

**Comment by michaelmacinnis** [comment]
@tw4452852 , @DeedleFake , when oh crashes and you are dumped back to the shell you used to launch oh, it would be helpful to see oh's exit status:

    echo $?

**Comment by tw4452852** [comment]
@michaelmacinnis of cause.

```sh
# this is in zsh
0> go version
go version devel +91977d0 Sat Nov 21 02:59:54 2015 +0000 linux/amd64

# launch oh
0> oh
> sleep 10 &
# when I press a key, like `d` in this case, `oh` exit and return to zsh
> d

# 0 is the $?, I set it in my zsh prompt by default
0> 
```

**Comment by michaelmacinnis** [comment]
Thanks @tw4452852 ,

Can you try setting the TERM environment variable to "dumb" and see if the problem persists:

    # launch oh
    TERM=dumb oh

**Comment by DeedleFake** [comment]
That fixes it. It breaks readline-style editing, though.

**Comment by michaelmacinnis** [comment]
Yeah, that work-around was just to narrow down the possibilities. I'll see what can be done to fix this.

**Comment by michaelmacinnis** [comment]
Thanks @DeedleFake , @tw4452852 ,

I've modified @peterh 's line editing library. Let me know if this fixes the problem and I will look at submitting a patch.

**Comment by michaelmacinnis** [comment]
@DeedleFake , @tw4452852 ,

Is the latest version of oh still exiting after launching a background command and pressing a key other than enter?

**Comment by tw4452852** [comment]
@michaelmacinnis  Sorry for late...
Now it works, I see your line editing library just works around this issue by restarting the loop when encounter the read error. Are there some reasons?

**Comment by michaelmacinnis** [comment]
@tw4452852 , not a problem. Thanks to you and @DeedleFake for reporting and helping me track down this problem. The solution (for now) basically involves resetting the foreground process group and the terminal mode on, but otherwise ignoring, errors other than EOF.
