### ISSUE TITLE
Prompt configuration

### ISSUE THREAD

**Issue by bpinto** [michaelmacinnis/oh#19]
Hi, I would like to use **oh** and having a configurable prompt is a must to me. What do you think?

I did some changes to the code and added the current directory to the "prompt":

```
oh > cd ~
bpinto > cd ~/src/
src >
```

Ideally, this would be configurable and colourful. :)

**Comment by michaelmacinnis** [comment]
Thanks for trying oh. I would welcome a pull request that adds a configurable prompt. Ideally this would be done by calling an oh method that the user can override.

**Comment by bpinto** [comment]
I am new to go and to oh, could you give me a top-level overview of the changes that would be necessary?

**Comment by michaelmacinnis** [comment]
Sure. You will need to modify ui.go to pass a prompt other than '> '. From
your last message it looks like you are comfortable doing that. What you
will want to do is add a function to task.go that evaluates a method in the
context of the foreground task and returns a string that can be used as the
prompt.

**Comment by michaelmacinnis** [comment]
The user can now define a prompt method (see lib/boot.oh for the default prompt method) to return a custom prompt.

**Comment by bpinto** [comment]
:+1:
