### ISSUE TITLE
pipe with user level cmd - security violation?

### ISSUE THREAD

**Issue by ljgww** [michaelmacinnis/oh#23]
Ubuntu 14.04

    >go version
    go version go1.7.4 linux/amd64

Oh:

    user> ls | grep old | wc -l
    oh: 4: error/runtime: fork/exec /usr/bin/wc: operation not permitted

**Comment by michaelmacinnis** [comment]
I can't reproduce this. Anything special about your setup?

**Comment by michaelmacinnis** [comment]
I'd love to hear from anyone who can reproduce this problem.
