### ISSUE TITLE
Strict modes like bash fam's set -euo pipefail?

### ISSUE THREAD

**Issue by mcandre** [michaelmacinnis/oh#24]
Could oh get strict modes equivalent to bash/ksh/zsh's `set -euo pipefail`, for protecting critical scripts?

**Comment by michaelmacinnis** [comment]
Good idea. Most of the pieces already exist. I'll have a more detailed response soon. Hopefully within the next few days.

**Comment by michaelmacinnis** [comment]
[Disclaimer: Oh is fairly stable. The documentation for oh is generated by a set of oh scripts that double as tests; repetitive Go code is generated by oh scripts; and much of oh is implemented in oh. But oh is still a work in progress and depending on your definition of "critical" you may want to consider using a more mature language.]

While making sure that what I was about to say was true I discovered an unexpected interaction between eval and the exceptions. With that fixed, here is how you could do something similar to set -euo pipefail:


set -u

By default, oh throws an exception if you attempt to set a variable that does not exist, access a non-existent member of an object or run a command that does not exist.

A symbol that has not been used as a variable name evaluates to itself. If this behavior is not strict enough you can enable "strict mode" by defining a variable with the name strict and setting it to a non-false value. In strict mode all barewords (command names, options) in the same lexical scope must be quoted strings:

    define strict = true
    "ls" "-la"

Strict mode is a subset of the default mode. Anything that will run in strict mode will run in the default mode.


set -o pipefail

This is now the default. We now rethrow the exception thrown by the leftmost command in a pipeline. If none of the commands throw an exception the exit status of the pipeline is set to the leftmost command to fail. If none of the commands fail the exit status of the pipeline is set to the exit status of the last (rightmost) command in the pipeline.
The "Maps" section of "Using oh" shows how to record the exit status for each stage in a pipeline.


set -e

I'm not a fan of this setting. I find it makes scripts too fragile. It is also difficult to implement correctly. Having said that, there is nothing stopping you from creating a wrapper translates non-successful exit codes into exceptions. Then just use this wrapper to launch any commands that should cause the script to abort on failure.

    define aof: syntax (: command) e = {
        define ec: e::eval @command
        if (not ec) {
            define name: command::head
            throw: exception "${name} failed with exit status ${ec}"
        }
    }
    aof: /bin/false
