### ISSUE TITLE
exits abruptly?

### ISSUE THREAD

**Issue by wmohanlon** [michaelmacinnis/oh#27]
Not sure if this is by design or not -- could just be a misunderstanding of intended behaviour.  While experimenting with the syntax, I noticed that a simple string ending with a colon drops me out of the shell.  e.g. "x:"

**Comment by michaelmacinnis** [comment]
That should be a syntax error. I will take a look. Thanks for letting me know.

**Comment by michaelmacinnis** [comment]
Should be fixed. If you run the latest version you should see:

    oh$ x:
    oh: 1: error/syntax: syntax error

Thanks again for reporting this.

**Comment by wmohanlon** [comment]
Looks good!  Thanks for the fix.  Apologies for my first comment being a bug report -- really enjoyed your BSDcan talk, and am looking forward to playing with oh.

**Comment by michaelmacinnis** [comment]
No need to apologize. If you notice anything else weird please don't hesitate to let me know. Thanks!
