### ISSUE TITLE
Oh returns error on Windows 10 (x64)

### ISSUE THREAD

**Issue by mitel-abku** [michaelmacinnis/oh#28]
When I tried to get latest version on Oh on my Windows 10 machine with x64 arch. First it asked me to enable 'object type list' flag needed by the OH utility and execute 'oh -otl' command to enable it. That will take effect next time you boot.

So after rebooting, I tried to access 'oh' via command-line but it returned 

```
> oh
RtlAdjustPrivilege(SE_DEBUG) failed with status = C0000061. -u may not work.//
// TIME: 2018-06-19 16:51
// MACHINE: LP-5CD7436N0Z
// BUILD: 9200
// OH version:  built by: dnsrv_dev(v-smgum)
//
//
```
followed by some kind of dump.

Then I tried to open the command-line using 'Run as administrator' but again got 

```
> oh
//
// TIME: 2018-06-19 16:55
// MACHINE: LP-5CD7436N0Z
// BUILD: 9200
// OH version:  built by: dnsrv_dev(v-smgum)
//
//
```

followed by some kind of dump.

Although 'oh  -help' command works and displays all the switches/options available and returns

```
> oh -help
oh - Object handles dump -- built by: dnsrv_dev(v-smgum)
Copyright (c) Microsoft Corporation. All rights reserved.

OH [DUMP_OPTIONS ...]
OH [FLAGS_OPTIONS ...]
OH -c [COMPARE_OPTIONS ...] BEFORE_LOG AFTER_LOG

DUMP_OPTIONS are:

    -p N - displays only open handles for process with ID of n. If not
           specified perform a system wide dump.
    -t TYPENAME - displays only open object names of specified type.
    -o FILENAME - specifies the name of the file to write the output to.
    -a includes objects with no name.
    -s display summary information
    -h display stack traces for handles (a process ID must be specified)
    -u display only handles with no references in process memory
    -v verbose mode (used for debugging oh)
    NAME - displays only handles that contain the specified name.

FLAGS_OPTIONS are:

    [+kst|-kst] - enable or disable kst flag (kernel mode stack traces).
    [+otl|-otl] - enable or disable otl flag (object lists).

The `OH [+otl] [+kst]' command can be used to set the global flags
needed by OH. `+otl' is needed for all OH options and `+kst' is needed
by the `-h' option. The changes will take effect only after reboot.
The flags can be disabled by using `-otl' or `-kst' respectively.

COMPARE_OPTIONS are:

    -l     Print most interesting increases in a separate initial section.
    -t     Do not add TRACE id to the names if files contain traces.
    -all   Report decreases as well as increases.

If the OH files have been created with -h option (they contain traces)
then handle names will be printed using this syntax: (TRACEID) NAME.
In case of a potential leak just search for the TRACEID in the original
OH file to find the stack trace.
```

**Comment by michaelmacinnis** [comment]
Looks like you are running a program called 'object handles dump' not the shell oh.

If you have installed github.com/michaelmacinnis/oh and are trying to run it, it looks like there is a problem finding the executable.

If you looking for help with 'object handles dump' you will need to find the maintainer of that program.

**Comment by mitel-abku** [comment]
Yes, thanks for pointing it out! 

It seems that there is another program with the same name from which it's name is conflicting. 

Now I have renamed that program to resolve the conflict.

So **oh** is actually stated running but it shows this error

```
C:\>oh
boot.oh: 485: error/runtime: 'HOME' undefined
C:\$
```

**Comment by michaelmacinnis** [comment]
Thank you for your interest in oh. As mentioned in the README, oh compiles and runs but should be considered experimental on Windows. If you are interested in solving issues you discover, pull requests are welcome.
