### ISSUE TITLE
Collaboration with Elvish project?

### ISSUE THREAD

**Issue by notramo** [michaelmacinnis/oh#29]
There is another modern shell, written in Go: https://elv.sh
It seems to me more mature, and also has very good ideas.
I don't see any advantages of having two shells developed independently, both are written in Go, with similar ideas, and both lacking developers. What do you think merging the ideas from one shell to the other, and developing it together with @xiaq?

**Comment by michaelmacinnis** [comment]
From what (admittedly little) I know about _elvish_, it seems to be focused primarily on improving the Unix shells interactive features. _Oh_ to date has focused on improving the Unix shell as a programming language. I believe @Solitude is correct (elves/elvish#713) the language features of _oh_ and _elvish_ are quite different. Similar in spirit; different in detail. And the devil is in the details.

**Comment by SolitudeSF** [comment]
elvish too is trying to be a better programming language, but the elvish and oh are already very different.

**Comment by michaelmacinnis** [comment]
Thanks @notramo. If you see areas where the two shells could benefit by sharing code please let me know. Pull requests are welcome!

**Comment by xiaq** [comment]
A bit late to the party :)

As much as I would love to see collaborations, IMO the design space for "a modern shell with a decent UI and language" is quite open and many different approaches exist. Elvish and Oh do have a lot in common, but they also differ in some key design decisions, and those different decisions are equally valid. According to my limited understanding Oh is quite minimalistic (not surprising given its Scheme heritage), while Elvish comes with a lot of batteries included.

I don't expect to see any kind of convergence on the language designs any time soon. I do see one area that can benefit from sharing code: I am rewriting Elvish's line editor, by first building a generic, language-agnostic line editor library, and using it as a basis for Elvish's line editor. AFAIK Oh does not have a line editor and could probably benefit from having one.

**Comment by michaelmacinnis** [comment]
Hi @xiaq,

Good luck with the line-editor library! Before you start building it you might want to take a look at the cross-platform line editing library oh uses: [liner](guthub.com/peterh/liner). It's used in hundreds of other projects: [](https://godoc.org/github.com/peterh/liner?importers)

Are you sure you'll have the time to support a generic, language-agnostic line editor library in addition to Elvish? I tried Elvish for the first time yesterday. While in vi I accidentally hit Ctrl-Z which hung the shell. You might want to throw in a few more batteries. ;-)

**Comment by xiaq** [comment]
Thanks, I wasn't aware of liner before (nor the fact that Oh uses liner).

I looked at Liner's API doc, it is pretty decent. Elvish's line editor does have more features though. It supports syntax highlighting, a right-hand prompt, refreshing of (left-hand and right-hand) prompts during a read cycle, custom key binding, a custom "listing area" (used to implement things like navigation mode and location mode; see "terminal shots" on https://elv.sh).

Regarding supporting a generic line editor library, it can be costly, but probably not as costly as you might imagine. Elvish itself needs a line editor, and it is good software engineering to first build a language-agnostic core and then add Elvish-specific stuff as "peripherals". So such a library will need to exist anyway. The costly part is maintaining a stable public API, but that doesn't have to be there on day 1. I can evolve the language-agnostic core along with Elvish itself and only declare that the API is stable when I feel it is mature enough.

Regarding the ^Z issue, I cannot reproduce that. Do you mind opening an issue on Elvish's [issue tracker](https://github.com/elves/elvish/issues)? Thanks!
