### ISSUE TITLE
Rewrite parser/lexer

### ISSUE THREAD

**Issue by michaelmacinnis** [michaelmacinnis/oh#30]
The current parser is generated using ohyacc, a version of goyacc that has been modified to allow:
- The lexer to trigger the parser to exit abnormally (Ctrl-C pressed).
- The parser to restart with a clear state for each command.

Additionally the lexer/parser have been hacked at to allow a partial parse in order to generate better completion candidates.

This works but a hand-written parser and a lexer that doesn't have to work around the constraints imposed by yacc would allow for more fine-grained control and, hopefully, less convoluted code.

**Comment by rain-1** [comment]
perhaps this parser library would be useful https://github.com/yhirose/go-peg

**Comment by michaelmacinnis** [comment]
Working on a new hand-written lexer and recursive descent parser.
