### ISSUE TITLE
Losing [my]self hacking oh :)

### ISSUE THREAD

**Issue by cryptorick** [michaelmacinnis/oh#36]
Hi!  This all started when I wanted to reduce the noise of `... | while (define ln: readline) ...`; so, I created a function abstraction to help the cause.  (Yeah, yeah, I know: one person's noise is another person's music. :)
```
$ define mapl: method (f) = : while (define ln: readline): $f $ln
```
And in case `f` doesn't print/echo anything, but we want to use its value down the pipeline, there is a variant which prints `f`'s images.
```
$ define maplp: method (f) = : while (define ln: readline): echo: $f $ln
```
Works look a charm!
```
$ echo rick michael | xargs -n1 | mapl: method (x) = : echo "-->" $x
--> rick
--> michael
```
The more common use case for me is that such a function is already defined, as so.
```
$ define echo-with-arrow: method (:args) = : echo "-->" @$args
```
Then, the pipeline works the same as before -- no surprises.
```
$ echo rick michael | xargs -n1 | mapl $echo-with-arrow
--> rick
--> michael
```
Now, here's where things start to get interesting: I needed a little caching mechanism that spied on items coming down that pipeline and "remembered" "seeing" those items.  Here's what I used.
```
$ define things-seen: method () =: object {
$     define what-seen: list
$ 
$     export show: method self () = {
$         echo $self::what-seen
$     }
$     export seen-this?: method self (this) = {
$         member? $this $self::what-seen
$     }
$     export see-this: method self (this) = {
$         if (not: seen-this? $this) {
$             set $self::what-seen: cons $this $self::what-seen
$         }
$         return $this
$     }
$ }
```
Oh yeah, you're gonna need this dependency too (list membership predicate).
```
$ define member: method (x xs) = {
$     if (or (is-null $xs) (eq $x : xs::head)) {
$         return $xs
$     } else {
$         member $x : xs::tail
$     }
$ }
$ define member?: method (:args) = : boolean : member @$args
```
Here's a non-pipeline usage, to get an idea.
```
$ define seen: things-seen
$ seen::show
()
$ seen::see-this "rick"
$ seen::see-this "michael"
$ seen::show
"michael" "rick"
```
Now, when we stick it in the pipeline with `mapl`, we'll see some sparks flying. :)
```
$ echo rick michael | xargs -n1 | maplp $seen::see-this
xargs: /bin/echo: terminated with signal 13; aborting
issue-minimal-example.oh: 25: error/runtime: 'what-seen' undefined
```
Oops.  It's as if we are losing track of that "slot" in the object -- actually, I think we've lost the `self` reference somehow, but that's just a guess.

Replacing `mapl` with what it's supposed to do, all is right again.
```
$ echo rick michael | xargs -n1 | while (define ln: readline): echo: $seen::see-this $ln
rick
michael
```
(BTW, I checked that the caching was also happening. :)

So, what am I doing wrong?

Here's the code all in one place to plop into a file, for convenience.  Thanks! --Rick

```
define mapl: method (f) = : while (define ln: readline): $f $ln

define maplp: method (f) = : while (define ln: readline): echo: $f $ln

define member: method (x xs) = {
    if (or (is-null $xs) (eq $x : xs::head)) {
        return $xs
    } else {
        member $x : xs::tail
    }
}
define member?: method (:args) = : boolean : member @$args

define things-seen: method () =: object {
    define what-seen: list

    export show: method self () = {
        echo $self::what-seen
    }
    export seen-this?: method self (this) = {
        member? $this $self::what-seen
    }
    export see-this: method self (this) = {
        if (not: seen-this? $this) {
            set $self::what-seen: cons $this $self::what-seen
        }
        return $this
    }
}

define echo-with-arrow: method (:args) = : echo "-->" @$args

# These both give same output (of course).
# $ echo rick michael | xargs -n1 | mapl: method (x) = : echo "-->" $x
# $ echo rick michael | xargs -n1 | mapl $echo-with-arrow

# Make an instance of things-seen (for use in the next two pipeline commands).
# $ define seen: things-seen

# This blows up.
# $ echo rick michael | xargs -n1 | maplp $seen::see-this

# This doesn't.
# $ echo rick michael | xargs -n1 | while (define ln: readline): echo: $seen::see-this $ln

```

**Comment by michaelmacinnis** [comment]
You can think of self in oh as _where did you find this?_ (Whereas the calling environment is _where did you come from_). When you pass `$seen::see-this` to `maplp` you are effectively pulling the method out of the object `$seen` and placing it in a new object (the environment created when you call `maplp`). When `maplp` calls `$f` self is the environment where `$f` was found. Like they say, "All problems in computer science can be solved by another level of indirection". You just need a level of indirection to keep the method bound to `$seen`:

define see-this: method (:args) =: $seen::see-this @$args
echo rick michael | xargs -n1 | maplp $see-this

**Comment by cryptorick** [comment]
Ah ok, thanks, @michaelmacinnis!

What you said about "effectively pulling the method out of the object `$seen` and placing it in a new object" is confirmed by this little example.
```
$ echo $seen::see-this
%bound 0xc42012c8a0%
$ echo-with-arrow $seen::see-this
--> %bound 0xc420083e80%
```

Also, what you said explains why going to macros works.
```
$ define maplp: syntax (f) e = {
$     e::eval: list while (list define ln (list readline)) (list echo (list $f (quote $ln)))
$ }
$ echo rick michael | xargs -n1 | maplp $seen::see-this
rick
michael
```
Thanks, again!

**Comment by michaelmacinnis** [comment]
Apologies for the short answer to your question and fantastic analysis. Really neat to see someone (other than myself) spend this much time with oh. I meant to follow up later in the week when I had more time and not (as is now the case) a month later.

This behaviour is caused by the interaction between three things in oh. The first being that environments and objects are the same thing. The second being that when a method is invoked without an explicit receiver self is set to the current lexical environment. ("Where did you find this?")

And the third being how delegation is handled in prototype-based languages like oh. The occurrences of self in a method refer to the original receiver and not the donor. See the slide "Delegation and Self" [here](http://lucacardelli.name/Talks/1996-05%20Class-based%20vs%20Object-based%20Languages%20(PLDI%20Tutorial).pdf).
