### ISSUE TITLE
Please make a Release

### ISSUE THREAD

**Issue by knusbaum** [michaelmacinnis/oh#38]
Thanks for your work, I really like this concept!
I would like to use oh, and create a package for it for Void Linux (voidlinux.org).

I'd really appreciate if you could make some sort of release. Policy in the distro repository makes it difficult to commit a package build if there is no versioned release. There don't need to be binaries, Basically just a source tarball with a version number. 

Thanks!

**Comment by michaelmacinnis** [comment]
Thanks! Let me know if this works: https://github.com/michaelmacinnis/oh/releases/tag/v0.4.8.16

**Comment by knusbaum** [comment]
Perfect. That works just fine. 

Thanks again for this and your work on this project.
