### ISSUE TITLE
support / ignore -i flag

### ISSUE THREAD

**Issue by gdiazlo** [michaelmacinnis/oh#39]
Some programs execute shells expecting the -i flag to instruct the shell to go into interactive mode. Can oh be instructed to ignore such flag?

**Comment by michaelmacinnis** [comment]
I think we could make oh respect the -i flag. In main, there is a call to task.StartNonInteractive() if len(os.Args) > 1. We could add a check to make sure we haven't been passed a -i.

**Comment by gdiazlo** [comment]
Cool!  Do you have any plans regarding oh flags? I can make this change in a PR using the flags package. Do you accept contributions this way?

btw, I'm working on converting my ~/.profile to an ohrc and I'm finding oh quite fun! :) thanks!

**Comment by michaelmacinnis** [comment]
A PR would be great. The only flag that oh currently parses is ```-c command```. If support for ```-i``` is added using the flags package it would be nice if ```-c``` was handled in the same way.

Let me know if you run into any problems converting your ```.profile``` to an ```.ohrc```. I'm still working on reducing the differences between oh and other Unix shells.

**Comment by gdiazlo** [comment]
I have a PR, it would be nice to have a way to pass all the tests after this kind of changes. Have you considered having a build/test pipeline somewhere to run  automated tests?

**Comment by michaelmacinnis** [comment]
There are automated test but they are more end to end tests of the language. They are written in oh and run when ```go generate``` is invoked as they also generate the documentation. There are no ```go test``` type tests. I agree, it would be nice if there were. Particularly for the job control features.
