### ISSUE TITLE
Please release `oh` binaries (like many Go projects do) 

### ISSUE THREAD

**Issue by mindreframer** [michaelmacinnis/oh#42]
First: thank you for putting this quite interesting bash alternative out there! To foster more adoption I would suggest to generate ready platform specific binaries, so it would be much simpler to test oh without having to install the Golang toolchain. 

To simplify it, one could use [Goreleaser](https://goreleaser.com/install/)

Cheers,
Roman

**Comment by mindreframer** [comment]
One example project: 
- https://github.com/kubernetes-sigs/kustomize/blob/master/releasing/cloudbuild.sh

**Comment by michaelmacinnis** [comment]
Thanks! Good idea. There are some fairly big changes coming to oh. I will look at providing precompiled binaries after those changes land.

**Comment by mindreframer** [comment]
Looking forward to it! :thumbs up:
