### ISSUE TITLE
What do you think of this project, I think I could use OH to make it super powerful 

### ISSUE THREAD

**Issue by Fransebas** [michaelmacinnis/oh#44]
https://github.com/Fransebas/sssh_distribution

It's basically a graphic interface for a shell,  I know it sounds contradictory but the idea is to help new people that are starting to learn how to use shells and people that are not computer scientist to use a shell.

The GUI helps with some commands that people don't born knowing and I just add the ability to add new interfaces.

OH could really help me because I had to find hacks for a lot of things that are not normally exposed on other shells for example getting and modifying the history in real time, updating the cwd, I tried but couldn't modify the environment variables from the GUI and I think that modifying the OH's code I could make amazing things, for example I could expose to the server as many things as needed for both reading and writing (like the env variables, cwd, history, etc), the shell would automatically send all the require data every time is updated without needing to put expensive hooks that have to be parse instead of being written directly in the shell code.

I would like to hear you opinion on the topic, OH is an amazing project.

**Comment by michaelmacinnis** [comment]
Sounds very cool. Not contradictory at all.

One comment: I couldn't find a license for your project? Have you considered adding one?

**Comment by Fransebas** [comment]
Oh (the expression) I forgot to add a license also I'm not sure of which one to choose between MIT or GNU

**Comment by michaelmacinnis** [comment]
The nice thing about the MIT license is that it's compatible with many other licenses.

**Comment by Fransebas** [comment]
I think I will put the MIT License.
Changing topic, can I use this issue to ask you high level question about Oh?

**Comment by michaelmacinnis** [comment]
Of course.

**Comment by Fransebas** [comment]
Would it be possible to create instances like this `ohShell := Oh{in:inputStream, out:outputStrem}` and keep all the functionality or do you think the only way is to create shells is by creating processes i.e. `exec("oh -i ...")` .

The question is because if the first option is posible, it will simplify the communication between the shell and the server, because the communication between them will be using events. And with the other method which is the one I'm currently using, the communication is using network request.

I think the first option will not be posible because when the ohShell changes it's context, like the user that is running, it will change the permissions of the whole server and other ohShell instances - for example changing the shell user from any user too the root user -, but that is just my thought without knowing the code.

I hope I was clear enough.

**Comment by michaelmacinnis** [comment]
One thing you could try is something that sits in between oh and its calls to liner - the command-line editing library that oh uses. This will let you know when oh is requesting another line or when oh wants to display a list of completions. There is already a very small wrapper around `*liner.State` called `ui` declared in main.go. It's probably easiest if you just start experimenting without worry about merging changes back upstream. Modify the code and add the hooks you need and once you have that working we can look at how to merge those changes.
