### ISSUE TITLE
openbsd amd64 ls

### ISSUE THREAD

**Issue by Don-Mickunas** [michaelmacinnis/oh#45]
I am running oh shell on a Dell Optiplex 990 on openbsd 6.8 amd64.  Regardless whether I install OH through the amd64 binary or through go, I get the following result when I attempt to issue the ls command:

root@openbsd:/root/go/bin>ls -l
total 7744
-rwxr-xr-x  1 root  wheel  3947543 Feb  8 14:12 oh
root@openbsd:/root/go/bin>./oh
don@openbsd.home:~/go/bin: ls
ls: unknown option -- -
usage: ls [-1AaCcdFfgHhikLlmnopqRrSsTtux] [file ...]
don@openbsd.home:~/go/bin: ls -l
ls: unknown option -- -
usage: ls [-1AaCcdFfgHhikLlmnopqRrSsTtux] [file ...]
don@openbsd.home:~/go/bin: 

I am able to use ls appropriately on Opensuse Linux.

**Comment by michaelmacinnis** [comment]
I blame it on me becoming too comfortable and Linux-centric on my current dev machine and adding this:
```
define ls: method ((args)) {
    command ls --color=auto (splice $args)
}
```
On your OpenBSD machine, after starting oh, can you try typing:
```
unset ls
```
and then see if you still get the same error message?

Alternatively. with the copy of oh you built from source can you try removing those 4 lines from internal/engine/boot/generated.go (on the main branch those are lines 621-624) and rebuilding oh.

**Comment by michaelmacinnis** [comment]
@Don-Mickunas did that fix the problem? Alternatively, try the latest release.

**Comment by Don-Mickunas** [comment]
Michael,

Thank you for checking back with me.  Life got in the way of me further exploring oh.  I chose to install the current version and all is good.  I look forward to playing with and exploring oh.  Thank you for a new shell.

Regards,

Don

**Comment by michaelmacinnis** [comment]
No problem. Thanks for trying oh. Let me know if you encounter anything else unexpected.
