### ISSUE TITLE
Configuration examples

### ISSUE THREAD

**Issue by rapha8l** [michaelmacinnis/oh#46]
Hi
Thanks for your work
Can you provide configuration examples ? (prompt, alias, functions, etc.)

Thanks

Raphael

**Comment by michaelmacinnis** [comment]
Hi,

Thanks for your interest in oh.

More docs are coming. For now checkout the [README](https://github.com/michaelmacinnis/oh/blob/main/README.md#configuring) for a prompt configuration example. The [manual](https://github.com/michaelmacinnis/oh/blob/main/doc/manual.md), while incomplete, should be at least be accurate. You can also take a look at the [boot.oh](https://github.com/michaelmacinnis/oh/blob/main/internal/engine/boot/boot.oh) script for more examples of oh code.

**Comment by rapha8l** [comment]
Ok thanks !
