### ISSUE TITLE
comparison with choc

### ISSUE THREAD

**Issue by eighal** [michaelmacinnis/oh#51]
Thank you for this very interesting project!

Is there a detailed comparison anywhere of oh with choc (as defined in your Masters thesis)?  Just for example, does oh have a built-in clone operation?

**Comment by michaelmacinnis** [comment]
Thanks for your interest. There is no detailed comparison of oh with choc. They are siblings so there are many similarities but there are also many differences. Oh did have a clone method but that was removed in the last round of cleanups as I found it was never used.

**Comment by eighal** [comment]
Thank you!
